
# ServerSettings
[server]
application_port = 8000
key_path = "/key.pem"
cert_path = "/cert.pem"

# DatabaseSettings
[database]
driver = "postgres"
host = "localhost"
port = 5432
username = "api"
password = "Bizowiefallout!5"
database_name = "api"

# TelemetrySettings
[telemetry]
env_filter = "error"             # options: error, info
